version: '3.5'
services:
    db:
        image: mysql/mysql-server:latest
        container_name: mysql
        build:
            context: .
            dockerfile: ./db.Dockerfile
        ports:
            - 127.0.0.1:3306:3306
        volumes:
             - db_data:/var/lib/mysql
        restart: on-failure
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        environment:
             - MYSQL_ROOT_PASSWORD=1234
        networks:
            - dev
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 60s
            retries: 10
    app:
        container_name: frontend_app
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:4545:4545
        restart: on-failure
        volumes:
            - api:/usr/src/bin
        depends_on:
            db:
                condition: service_healthy
        networks:
            - dev
volumes:
    db_data:
    api:
networks:
    dev:
        driver: bridge
