version: '3.5'
services:
    db:
        image: mysql/mysql-server:latest
        container_name: mysql
        ports:
            - 127.0.0.1:3169:3169
        volumes:
             - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
             - db_data:/var/lib/mysql
        restart: on-failure
        networks:
            - dev
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    app:
        container_name: frontend_app
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:4545:4545
        restart: on-failure
        volumes:
            - api:/usr/src/bin
        depends_on:
            db:
                condition: service_healthy
        networks:
            - dev
volumes:
    db_data:
    api:
networks:
    dev:
        driver: bridge
